/* =====================================================================
   THE CHARTERHOLDER — Level I drill bank (100 scenarios, ~10 per subject)
   Compact exam-style questions from the CFA L1 curriculum. Player calculates;
   each carries a fixed answer key + a worked solution. Pushed into the shared
   scenario bank so they interleave into the campaign (by subject) and appear
   subject-wise in Free Play.
   ===================================================================== */
window.GAME_CONTENT.scenarios.push(

/* ---------------- ETHICS (10) ---------------- */
{id:"l1d-eth-01", act:1, level:"L1", topic:"Ethics", reading:"Standard I(C) Misrepresentation", difficulty:"easy", type:"exam",
 title:"The Guaranteed Return",
 situation:"An adviser tells a prospect that a diversified equity fund \"will definitely return 12% every year.\" Which CFA Standard is most directly violated?",
 solution:"Standard I(C) Misrepresentation prohibits guaranteeing performance on risk assets. Equity returns cannot be promised.",
 choices:[{text:"Standard I(C) — Misrepresentation", correct:true},{text:"Standard III(A) — Loyalty, Prudence, and Care"},{text:"Standard IV(A) — Loyalty to Employer"},{text:"Standard II(A) — Material Nonpublic Information"}]},

{id:"l1d-eth-02", act:1, level:"L1", topic:"Ethics", reading:"Standard I(C) Misrepresentation (Plagiarism)", difficulty:"easy", type:"exam",
 title:"Borrowed Research",
 situation:"An analyst copies whole sections of another firm's report into her own note without attribution. This is a violation of:",
 solution:"Plagiarism — using others' work without acknowledgment — is a form of Misrepresentation under Standard I(C).",
 choices:[{text:"Standard III(B) — Fair Dealing"},{text:"Standard I(C) — Misrepresentation", correct:true},{text:"Standard V(A) — Diligence and Reasonable Basis"},{text:"No violation if the analysis is correct"}]},

{id:"l1d-eth-03", act:1, level:"L1", topic:"Ethics", reading:"Standard VI(B) Priority of Transactions", difficulty:"easy", type:"exam",
 title:"Front of the Queue",
 situation:"A portfolio manager buys a stock for his personal account the morning before placing the same buy order for client accounts. He violates:",
 solution:"Standard VI(B) Priority of Transactions requires client and employer transactions to take precedence over personal ones.",
 choices:[{text:"Standard VI(B) — Priority of Transactions", correct:true},{text:"Standard VI(A) — Disclosure of Conflicts"},{text:"Standard III(A) — Loyalty, Prudence, and Care"},{text:"Standard I(B) — Independence and Objectivity"}]},

{id:"l1d-eth-04", act:1, level:"L1", topic:"Ethics", reading:"Standard III(B) Fair Dealing", difficulty:"easy", type:"exam",
 title:"Who Hears It First",
 situation:"A firm emails a new Buy recommendation to its largest clients and only sends it to everyone else the next day. This most likely violates:",
 solution:"Standard III(B) Fair Dealing requires recommendations be disseminated to all clients fairly and simultaneously; selective early disclosure is prohibited.",
 choices:[{text:"Standard III(B) — Fair Dealing", correct:true},{text:"Standard III(C) — Suitability"},{text:"Standard VI(A) — Disclosure of Conflicts"},{text:"Standard I(C) — Misrepresentation"}]},

{id:"l1d-eth-05", act:1, level:"L1", topic:"Ethics", reading:"Standard IV(A) Loyalty to Employer", difficulty:"easy", type:"exam",
 title:"Moonlighting",
 situation:"While still employed, an analyst secretly solicits the firm's clients for a competing venture he plans to launch. He violates:",
 solution:"Standard IV(A) Loyalty (to Employer) prohibits activities that harm the employer, including soliciting its clients before departure.",
 choices:[{text:"Standard III(E) — Preservation of Confidentiality"},{text:"Standard IV(A) — Loyalty to Employer", correct:true},{text:"Standard VI(B) — Priority of Transactions"},{text:"No violation — clients can choose freely"}]},

{id:"l1d-eth-06", act:1, level:"L1", topic:"Ethics", reading:"Standard V(A) Diligence and Reasonable Basis", difficulty:"easy", type:"exam",
 title:"A Hunch, Not a Basis",
 situation:"An analyst issues a Buy on a company after reading only a single bullish tweet, doing no independent work. This violates:",
 solution:"Standard V(A) Diligence and Reasonable Basis requires a reasonable and adequate basis, supported by research, for any recommendation.",
 choices:[{text:"Standard V(A) — Diligence and Reasonable Basis", correct:true},{text:"Standard V(B) — Communication with Clients"},{text:"Standard I(A) — Knowledge of the Law"},{text:"Standard III(C) — Suitability"}]},

{id:"l1d-eth-07", act:1, level:"L1", topic:"Ethics", reading:"Standard III(E) Preservation of Confidentiality", difficulty:"easy", type:"exam",
 title:"Loose Lips",
 situation:"An adviser shares a client's confidential financial details with a friend at a dinner party. This violates:",
 solution:"Standard III(E) Preservation of Confidentiality requires keeping client information confidential unless disclosure is required by law or authorized by the client.",
 choices:[{text:"Standard III(A) — Loyalty, Prudence, and Care"},{text:"Standard VI(A) — Disclosure of Conflicts"},{text:"Standard III(E) — Preservation of Confidentiality", correct:true},{text:"Standard IV(B) — Additional Compensation"}]},

{id:"l1d-eth-08", act:1, level:"L1", topic:"Ethics", reading:"Introduction to GIPS", difficulty:"easy", type:"exam",
 title:"What GIPS Is",
 situation:"Which statement about the Global Investment Performance Standards (GIPS) is correct?",
 solution:"GIPS compliance is voluntary and must be applied on a firm-wide basis; a firm cannot claim partial compliance.",
 choices:[{text:"GIPS is voluntary and applied on a firm-wide basis", correct:true},{text:"GIPS is mandatory for all CFA charterholders"},{text:"A firm may claim compliance for selected composites only"},{text:"GIPS applies only to hedge funds"}]},

{id:"l1d-eth-09", act:1, level:"L1", topic:"Ethics", reading:"Standard I(A) Knowledge of the Law", difficulty:"moderate", type:"exam",
 title:"Which Law Governs",
 situation:"A member works where local law is less strict than the Code and Standards, and no law dictates otherwise. Which must the member follow?",
 solution:"Standard I(A): when the applicable law is less strict than the Code and Standards, members must adhere to the stricter Code and Standards.",
 choices:[{text:"The stricter Code and Standards", correct:true},{text:"The less-strict local law"},{text:"Whichever is easier to document"},{text:"Neither, if the client consents"}]},

{id:"l1d-eth-10", act:1, level:"L1", topic:"Ethics", reading:"Standard III(C) Suitability", difficulty:"easy", type:"exam",
 title:"Fit for the Client",
 situation:"An adviser places a conservative retiree's savings into a concentrated, speculative small-cap position for the higher potential return. This violates:",
 solution:"Standard III(C) Suitability requires recommendations to fit the client's objectives, constraints and risk tolerance as set out in the IPS.",
 choices:[{text:"Standard III(C) — Suitability", correct:true},{text:"Standard V(A) — Diligence and Reasonable Basis"},{text:"Standard I(B) — Independence and Objectivity"},{text:"No violation if returns are high"}]},

/* ---------------- QUANTITATIVE METHODS (10) ---------------- */
{id:"l1d-qm-01", act:1, level:"L1", topic:"Quantitative Methods", reading:"1.01 Rates and Returns", difficulty:"easy", type:"exam",
 title:"Holding Period Return",
 situation:"You buy a share at $50, receive a $1 dividend, and sell at $55. What is the holding period return?",
 exhibit:{title:"Data", rows:[["Purchase price","$50"],["Dividend","$1"],["Sale price","$55"]]},
 solution:"HPR = (P₁ − P₀ + D) / P₀ = (55 − 50 + 1)/50 = 6/50 = 12.0%.",
 choices:[{text:"12.0%", correct:true},{text:"10.0%"},{text:"11.0%"},{text:"12.2%"}]},

{id:"l1d-qm-02", act:1, level:"L1", topic:"Quantitative Methods", reading:"1.01 Rates and Returns", difficulty:"easy", type:"exam",
 title:"Real Plus Inflation",
 situation:"If the real risk-free rate is 2% and expected inflation is 3%, the approximate nominal risk-free rate (additive) is:",
 solution:"Nominal ≈ real + inflation = 2% + 3% = 5% (additive approximation). The exact figure is (1.02)(1.03) − 1 = 5.06%.",
 choices:[{text:"5.0%", correct:true},{text:"1.0%"},{text:"6.0%"},{text:"0.67%"}]},

{id:"l1d-qm-03", act:1, level:"L1", topic:"Quantitative Methods", reading:"1.01 Rates and Returns", difficulty:"moderate", type:"exam",
 title:"Geometric Mean",
 situation:"A portfolio returns +10% in year 1 and −5% in year 2. What is the geometric mean annual return?",
 solution:"Geometric mean = [(1.10)(0.95)]^(1/2) − 1 = (1.045)^0.5 − 1 = 1.02225 − 1 = 2.23%. It is below the 2.5% arithmetic mean.",
 choices:[{text:"2.23%", correct:true},{text:"2.50%"},{text:"5.00%"},{text:"7.50%"}]},

{id:"l1d-qm-04", act:1, level:"L1", topic:"Quantitative Methods", reading:"1.03 Statistical Measures of Asset Returns", difficulty:"easy", type:"exam",
 title:"Coefficient of Variation",
 situation:"An asset has a mean return of 8% and a standard deviation of 12%. Its coefficient of variation is:",
 solution:"CV = σ / mean = 12% / 8% = 1.5. It measures risk per unit of return; lower is better.",
 choices:[{text:"1.5", correct:true},{text:"0.67"},{text:"12.0"},{text:"0.96"}]},

{id:"l1d-qm-05", act:1, level:"L1", topic:"Quantitative Methods", reading:"1.03 Statistical Measures of Asset Returns", difficulty:"easy", type:"exam",
 title:"From Variance to Volatility",
 situation:"A return series has a variance of 0.0225. Its standard deviation is:",
 solution:"Standard deviation = √variance = √0.0225 = 0.15 = 15%.",
 choices:[{text:"15%", correct:true},{text:"1.5%"},{text:"22.5%"},{text:"0.15%"}]},

{id:"l1d-qm-06", act:1, level:"L1", topic:"Quantitative Methods", reading:"1.04 Probability Trees and Conditional Expectations", difficulty:"easy", type:"exam",
 title:"Both Events",
 situation:"Events A and B are independent with P(A) = 0.4 and P(B) = 0.5. What is P(A and B)?",
 solution:"For independent events, P(A ∩ B) = P(A) × P(B) = 0.4 × 0.5 = 0.20.",
 choices:[{text:"0.20", correct:true},{text:"0.90"},{text:"0.10"},{text:"0.70"}]},

{id:"l1d-qm-07", act:1, level:"L1", topic:"Quantitative Methods", reading:"1.05 Portfolio Mathematics", difficulty:"moderate", type:"exam",
 title:"Correlation from Covariance",
 situation:"Two assets have covariance 0.006, with standard deviations of 10% and 15%. Their correlation is:",
 solution:"ρ = Cov / (σ₁σ₂) = 0.006 / (0.10 × 0.15) = 0.006 / 0.015 = 0.40.",
 choices:[{text:"0.40", correct:true},{text:"0.06"},{text:"0.90"},{text:"0.04"}]},

{id:"l1d-qm-08", act:1, level:"L1", topic:"Quantitative Methods", reading:"1.07 Estimation and Inference", difficulty:"moderate", type:"exam",
 title:"Standard Error",
 situation:"A population has a standard deviation of 20. For a sample of 100 observations, the standard error of the mean is:",
 solution:"Standard error = σ / √n = 20 / √100 = 20 / 10 = 2.0.",
 choices:[{text:"2.0", correct:true},{text:"20.0"},{text:"0.2"},{text:"4.0"}]},

{id:"l1d-qm-09", act:1, level:"L1", topic:"Quantitative Methods", reading:"1.08 Hypothesis Testing", difficulty:"moderate", type:"exam",
 title:"The t-Statistic",
 situation:"A sample of 64 has mean 105 and standard deviation 20. Testing H₀: μ = 100, the test statistic is:",
 exhibit:{title:"Inputs", rows:[["Sample mean","105"],["Hypothesized mean","100"],["Sample std dev","20"],["n","64"]]},
 solution:"t = (x̄ − μ₀)/(s/√n) = (105 − 100)/(20/8) = 5 / 2.5 = 2.0.",
 choices:[{text:"2.0", correct:true},{text:"5.0"},{text:"0.4"},{text:"1.6"}]},

{id:"l1d-qm-10", act:1, level:"L1", topic:"Quantitative Methods", reading:"1.10 Simple Linear Regression", difficulty:"easy", type:"exam",
 title:"R-Squared to Correlation",
 situation:"A simple linear regression has R² = 0.64 with a positive slope. The correlation coefficient is:",
 solution:"In simple regression, correlation = ±√R². With a positive slope, r = +√0.64 = 0.80.",
 choices:[{text:"0.80", correct:true},{text:"0.64"},{text:"0.40"},{text:"0.36"}]},

/* ---------------- ECONOMICS (10) ---------------- */
{id:"l1d-ec-01", act:1, level:"L1", topic:"Economics", reading:"2.01 Firms and Market Structures", difficulty:"easy", type:"exam",
 title:"Elastic or Not",
 situation:"When a firm raises price 5%, quantity demanded falls 10%. The price elasticity of demand is:",
 solution:"|Elasticity| = %ΔQ / %ΔP = 10% / 5% = 2.0. Because it exceeds 1, demand is elastic.",
 choices:[{text:"2.0 — elastic", correct:true},{text:"0.5 — inelastic"},{text:"2.0 — inelastic"},{text:"0.5 — elastic"}]},

{id:"l1d-ec-02", act:1, level:"L1", topic:"Economics", reading:"2.01 Firms and Market Structures", difficulty:"easy", type:"exam",
 title:"Perfect Competition",
 situation:"Which is a defining feature of a perfectly competitive market?",
 solution:"In perfect competition, firms are price takers selling a homogeneous product; economic profit is zero in the long run.",
 choices:[{text:"Firms are price takers with zero long-run economic profit", correct:true},{text:"A single firm sets the market price"},{text:"Products are highly differentiated"},{text:"High barriers to entry"}]},

{id:"l1d-ec-03", act:1, level:"L1", topic:"Economics", reading:"2.02 Understanding Business Cycles", difficulty:"moderate", type:"exam",
 title:"The GDP Deflator",
 situation:"Nominal GDP is 110 and real GDP is 100. The GDP deflator is:",
 solution:"GDP deflator = (Nominal GDP / Real GDP) × 100 = (110/100) × 100 = 110, implying 10% cumulative inflation.",
 choices:[{text:"110", correct:true},{text:"100"},{text:"10"},{text:"90.9"}]},

{id:"l1d-ec-04", act:1, level:"L1", topic:"Economics", reading:"2.03 Fiscal Policy", difficulty:"easy", type:"exam",
 title:"Loosening the Purse",
 situation:"Which action is expansionary fiscal policy?",
 solution:"Expansionary fiscal policy increases aggregate demand via higher government spending or lower taxes.",
 choices:[{text:"Increasing government spending", correct:true},{text:"Raising income tax rates"},{text:"Selling government bonds to the public"},{text:"Raising the policy interest rate"}]},

{id:"l1d-ec-05", act:1, level:"L1", topic:"Economics", reading:"2.04 Monetary Policy", difficulty:"easy", type:"exam",
 title:"Draining Liquidity",
 situation:"To fight inflation, a central bank conducting open market operations would:",
 solution:"Contractionary policy: selling government securities drains reserves from the banking system, raising rates and slowing money growth.",
 choices:[{text:"Sell government securities", correct:true},{text:"Buy government securities"},{text:"Lower the reserve requirement"},{text:"Cut the policy rate"}]},

{id:"l1d-ec-06", act:1, level:"L1", topic:"Economics", reading:"2.04 Monetary Policy", difficulty:"moderate", type:"exam",
 title:"The Money Multiplier",
 situation:"If the required reserve ratio is 20%, the money multiplier is:",
 solution:"Money multiplier = 1 / reserve ratio = 1 / 0.20 = 5.",
 choices:[{text:"5", correct:true},{text:"20"},{text:"0.2"},{text:"4"}]},

{id:"l1d-ec-07", act:1, level:"L1", topic:"Economics", reading:"2.07 Capital Flows and the FX Market", difficulty:"moderate", type:"exam",
 title:"Interest Rate Parity",
 situation:"Under covered interest rate parity, the currency of the country with the higher nominal interest rate will trade at a:",
 solution:"Covered interest rate parity: the higher-yielding currency trades at a forward discount, offsetting the interest advantage so no arbitrage exists.",
 choices:[{text:"Forward discount", correct:true},{text:"Forward premium"},{text:"Spot premium only"},{text:"No forward adjustment"}]},

{id:"l1d-ec-08", act:1, level:"L1", topic:"Economics", reading:"2.08 Exchange Rate Calculations", difficulty:"moderate", type:"exam",
 title:"The Cross Rate",
 situation:"If GBP costs USD 1.25 and EUR costs USD 1.10, how many EUR does one GBP buy?",
 exhibit:{title:"Quotes (USD per unit)", rows:[["USD per GBP","1.25"],["USD per EUR","1.10"]]},
 solution:"EUR per GBP = (USD/GBP) ÷ (USD/EUR) = 1.25 / 1.10 = 1.136 EUR per GBP.",
 choices:[{text:"1.136", correct:true},{text:"0.88"},{text:"1.375"},{text:"1.10"}]},

{id:"l1d-ec-09", act:1, level:"L1", topic:"Economics", reading:"2.02 Understanding Business Cycles", difficulty:"easy", type:"exam",
 title:"Ahead of the Curve",
 situation:"Which of the following is a leading economic indicator?",
 solution:"Building permits (and new orders, stock prices) lead the cycle; unemployment is a lagging indicator and industrial production is roughly coincident.",
 choices:[{text:"New building permits", correct:true},{text:"The unemployment rate"},{text:"Industrial production"},{text:"Average duration of unemployment"}]},

{id:"l1d-ec-10", act:1, level:"L1", topic:"Economics", reading:"2.06 International Trade", difficulty:"easy", type:"exam",
 title:"Where to Specialize",
 situation:"According to comparative advantage, a country should specialize in producing goods for which it has:",
 solution:"Comparative advantage means the lower opportunity cost of production; trade then benefits both countries even if one has an absolute advantage in everything.",
 choices:[{text:"The lower opportunity cost", correct:true},{text:"The higher opportunity cost"},{text:"The largest population"},{text:"The highest wages"}]},

/* ---------------- FINANCIAL REPORTING (11) ---------------- */
{id:"l1d-fr-01", act:1, level:"L1", topic:"Financial Reporting", reading:"5.11 Financial Analysis Techniques", difficulty:"easy", type:"exam",
 title:"Current Ratio",
 situation:"Current assets are $300 and current liabilities are $150. The current ratio is:",
 solution:"Current ratio = Current assets / Current liabilities = 300 / 150 = 2.0.",
 choices:[{text:"2.0", correct:true},{text:"0.5"},{text:"1.5"},{text:"450"}]},

{id:"l1d-fr-02", act:1, level:"L1", topic:"Financial Reporting", reading:"5.02 Analyzing Income Statements", difficulty:"easy", type:"exam",
 title:"Gross Margin",
 situation:"Revenue is $500 and COGS is $300. The gross profit margin is:",
 solution:"Gross profit = 500 − 300 = 200. Gross margin = 200 / 500 = 40%.",
 choices:[{text:"40%", correct:true},{text:"60%"},{text:"20%"},{text:"166%"}]},

{id:"l1d-fr-03", act:1, level:"L1", topic:"Financial Reporting", reading:"5.02 Analyzing Income Statements", difficulty:"easy", type:"exam",
 title:"Net Margin",
 situation:"Net income is $50 on revenue of $500. The net profit margin is:",
 solution:"Net margin = Net income / Revenue = 50 / 500 = 10%.",
 choices:[{text:"10%", correct:true},{text:"20%"},{text:"5%"},{text:"1000%"}]},

{id:"l1d-fr-04", act:1, level:"L1", topic:"Financial Reporting", reading:"5.06 Analysis of Inventories", difficulty:"easy", type:"exam",
 title:"Inventory Turnover",
 situation:"COGS is $300 and average inventory is $60. Inventory turnover is:",
 solution:"Inventory turnover = COGS / Average inventory = 300 / 60 = 5.0×.",
 choices:[{text:"5.0×", correct:true},{text:"0.2×"},{text:"60×"},{text:"8.3×"}]},

{id:"l1d-fr-05", act:1, level:"L1", topic:"Financial Reporting", reading:"5.11 Financial Analysis Techniques", difficulty:"easy", type:"exam",
 title:"Days of Inventory",
 situation:"If inventory turnover is 5.0, the days of inventory on hand (365-day year) is approximately:",
 solution:"Days of inventory = 365 / turnover = 365 / 5 = 73 days.",
 choices:[{text:"73 days", correct:true},{text:"5 days"},{text:"60 days"},{text:"50 days"}]},

{id:"l1d-fr-06", act:1, level:"L1", topic:"Financial Reporting", reading:"5.11 Financial Analysis Techniques (DuPont)", difficulty:"moderate", type:"exam",
 title:"Return on Equity",
 situation:"Net income is $50 and average shareholders' equity is $250. ROE is:",
 solution:"ROE = Net income / Average equity = 50 / 250 = 20%.",
 choices:[{text:"20%", correct:true},{text:"10%"},{text:"5%"},{text:"25%"}]},

{id:"l1d-fr-07", act:1, level:"L1", topic:"Financial Reporting", reading:"5.07 Analysis of Long-Term Assets", difficulty:"easy", type:"exam",
 title:"Straight-Line Depreciation",
 situation:"An asset costs $100,000, has a $10,000 salvage value and a 9-year life. Annual straight-line depreciation is:",
 exhibit:{title:"Inputs", rows:[["Cost","$100,000"],["Salvage value","$10,000"],["Useful life","9 years"]]},
 solution:"Depreciation = (Cost − Salvage)/Life = (100,000 − 10,000)/9 = 90,000/9 = $10,000 per year.",
 choices:[{text:"$10,000", correct:true},{text:"$11,111"},{text:"$9,000"},{text:"$12,222"}]},

{id:"l1d-fr-08", act:1, level:"L1", topic:"Financial Reporting", reading:"5.04 Analyzing Statements of Cash Flows I", difficulty:"moderate", type:"exam",
 title:"Where Do Dividends Go?",
 situation:"Under US GAAP, dividends PAID to shareholders are classified in the statement of cash flows as:",
 solution:"US GAAP classifies dividends paid as a financing outflow. (Under IFRS, they may be operating or financing.)",
 choices:[{text:"Financing activities", correct:true},{text:"Operating activities"},{text:"Investing activities"},{text:"They are not a cash flow"}]},

{id:"l1d-fr-09", act:1, level:"L1", topic:"Financial Reporting", reading:"5.06 Analysis of Inventories (LIFO reserve)", difficulty:"moderate", type:"exam",
 title:"Restating to FIFO",
 situation:"A US firm reports LIFO inventory of $100 and a LIFO reserve of $20. Inventory restated to FIFO is:",
 solution:"FIFO inventory = LIFO inventory + LIFO reserve = 100 + 20 = $120.",
 choices:[{text:"$120", correct:true},{text:"$80"},{text:"$100"},{text:"$20"}]},

{id:"l1d-fr-10", act:1, level:"L1", topic:"Financial Reporting", reading:"5.11 Financial Analysis Techniques", difficulty:"easy", type:"exam",
 title:"Interest Coverage",
 situation:"EBIT is $120 and interest expense is $30. The interest coverage ratio is:",
 solution:"Interest coverage = EBIT / Interest expense = 120 / 30 = 4.0×.",
 choices:[{text:"4.0×", correct:true},{text:"0.25×"},{text:"3.0×"},{text:"150×"}]},

{id:"l1d-fr-11", act:1, level:"L1", topic:"Financial Reporting", reading:"5.02 Analyzing Income Statements (EPS)", difficulty:"moderate", type:"exam",
 title:"Basic EPS",
 situation:"Net income is $100,000, preferred dividends are $10,000, and the weighted-average common shares outstanding are 45,000. Basic EPS is:",
 exhibit:{title:"Inputs", rows:[["Net income","$100,000"],["Preferred dividends","$10,000"],["Weighted-avg common shares","45,000"]]},
 solution:"Basic EPS = (Net income − Preferred dividends) / Weighted-avg common shares = (100,000 − 10,000)/45,000 = 90,000/45,000 = $2.00.",
 choices:[{text:"$2.00", correct:true},{text:"$2.22"},{text:"$1.80"},{text:"$2.44"}]},

/* ---------------- CORPORATE ISSUERS (10) ---------------- */
{id:"l1d-ci-01", act:1, level:"L1", topic:"Corporate Issuers", reading:"4.05 Capital Investments and Capital Allocation", difficulty:"moderate", type:"exam",
 title:"Net Present Value",
 situation:"A project costs $1,000 today and returns a single $1,150 cash flow in one year. At a 10% required return, NPV is:",
 exhibit:{title:"Inputs", rows:[["Initial outlay","$1,000"],["Inflow in 1 year","$1,150"],["Required return","10%"]]},
 solution:"NPV = −1,000 + 1,150/1.10 = −1,000 + 1,045.45 = $45.45. Positive NPV → accept.",
 choices:[{text:"$45.45", correct:true},{text:"$150.00"},{text:"$50.00"},{text:"−$45.45"}]},

{id:"l1d-ci-02", act:1, level:"L1", topic:"Corporate Issuers", reading:"4.05 Capital Investments and Capital Allocation", difficulty:"easy", type:"exam",
 title:"The IRR Rule",
 situation:"Using the internal rate of return (IRR) criterion, an independent project should be accepted when:",
 solution:"IRR is the discount rate that makes NPV = 0. Accept an independent project when IRR exceeds the required rate of return (hurdle rate).",
 choices:[{text:"IRR exceeds the required rate of return", correct:true},{text:"IRR is below the required rate of return"},{text:"IRR equals zero"},{text:"IRR is negative"}]},

{id:"l1d-ci-03", act:1, level:"L1", topic:"Corporate Issuers", reading:"4.05 Capital Investments and Capital Allocation", difficulty:"easy", type:"exam",
 title:"Payback Period",
 situation:"A project costs $1,000 and generates $400 per year. Its payback period is:",
 solution:"Payback = Initial cost / Annual cash flow = 1,000 / 400 = 2.5 years.",
 choices:[{text:"2.5 years", correct:true},{text:"2.0 years"},{text:"3.0 years"},{text:"4.0 years"}]},

{id:"l1d-ci-04", act:1, level:"L1", topic:"Corporate Issuers", reading:"4.06 Capital Structure (WACC)", difficulty:"moderate", type:"exam",
 title:"Weighted Average Cost of Capital",
 situation:"Equity is 60% of capital at a 12% cost; debt is 40% at a 6% pre-tax cost; the tax rate is 25%. WACC is:",
 exhibit:{title:"Inputs", rows:[["Weight of equity","60%"],["Cost of equity","12%"],["Weight of debt","40%"],["Pre-tax cost of debt","6%"],["Tax rate","25%"]]},
 solution:"WACC = wₑ·rₑ + w_d·r_d·(1−t) = 0.60×12% + 0.40×6%×(1−0.25) = 7.2% + 1.8% = 9.0%.",
 choices:[{text:"9.0%", correct:true},{text:"9.6%"},{text:"10.8%"},{text:"7.2%"}]},

{id:"l1d-ci-05", act:1, level:"L1", topic:"Corporate Issuers", reading:"4.06 Capital Structure", difficulty:"easy", type:"exam",
 title:"After-Tax Cost of Debt",
 situation:"A firm's pre-tax cost of debt is 8% and its tax rate is 25%. Its after-tax cost of debt is:",
 solution:"After-tax cost of debt = r_d × (1 − t) = 8% × (1 − 0.25) = 6.0%.",
 choices:[{text:"6.0%", correct:true},{text:"8.0%"},{text:"2.0%"},{text:"10.0%"}]},

{id:"l1d-ci-06", act:1, level:"L1", topic:"Corporate Issuers", reading:"4.07 Business Models / Operating Leverage", difficulty:"easy", type:"exam",
 title:"Operating Leverage",
 situation:"Everything else equal, which firm has the higher business (operating) risk?",
 solution:"Higher fixed costs raise the degree of operating leverage, magnifying the effect of sales changes on operating income and increasing business risk.",
 choices:[{text:"The one with higher fixed costs", correct:true},{text:"The one with higher variable costs"},{text:"The one with lower fixed costs"},{text:"Operating leverage does not affect risk"}]},

{id:"l1d-ci-07", act:1, level:"L1", topic:"Corporate Issuers", reading:"4.04 Working Capital and Liquidity", difficulty:"easy", type:"exam",
 title:"Net Working Capital",
 situation:"Current assets are $300 and current liabilities are $180. Net working capital is:",
 solution:"Net working capital = Current assets − Current liabilities = 300 − 180 = $120.",
 choices:[{text:"$120", correct:true},{text:"$480"},{text:"$1.67"},{text:"$0"}]},

{id:"l1d-ci-08", act:1, level:"L1", topic:"Corporate Issuers", reading:"4.03 Corporate Governance", difficulty:"easy", type:"exam",
 title:"The Agency Problem",
 situation:"The principal–agent conflict in a corporation most directly arises between:",
 solution:"The classic agency problem is between shareholders (principals) and managers (agents), whose interests can diverge from those of owners.",
 choices:[{text:"Shareholders and managers", correct:true},{text:"Customers and suppliers"},{text:"Employees and regulators"},{text:"Auditors and tax authorities"}]},

{id:"l1d-ci-09", act:1, level:"L1", topic:"Corporate Issuers", reading:"4.06 Capital Structure (MM)", difficulty:"moderate", type:"exam",
 title:"Modigliani–Miller, No Taxes",
 situation:"Under Modigliani–Miller with no taxes and no other frictions, a firm's capital structure is:",
 solution:"MM Proposition I (no taxes): firm value is independent of capital structure. With taxes, the interest tax shield makes some debt value-adding.",
 choices:[{text:"Irrelevant to firm value", correct:true},{text:"Optimized at 100% debt"},{text:"Optimized at 100% equity"},{text:"Always improved by more debt"}]},

{id:"l1d-ci-10", act:1, level:"L1", topic:"Corporate Issuers", reading:"4.04 Working Capital and Liquidity", difficulty:"moderate", type:"exam",
 title:"Cash Conversion Cycle",
 situation:"Days of inventory = 40, days of receivables = 30, days of payables = 25. The cash conversion cycle is:",
 solution:"CCC = DOH + DSO − DPO = 40 + 30 − 25 = 45 days.",
 choices:[{text:"45 days", correct:true},{text:"95 days"},{text:"35 days"},{text:"40 days"}]},

/* ---------------- EQUITY (10) ---------------- */
{id:"l1d-eq-01", act:1, level:"L1", topic:"Equity", reading:"6.02 Security Market Indexes", difficulty:"easy", type:"exam",
 title:"Price-Weighted Index",
 situation:"A price-weighted index holds three stocks priced $10, $20 and $30, with a divisor of 3. The index value is:",
 solution:"Price-weighted index = Σ prices / divisor = (10 + 20 + 30)/3 = 60/3 = 20.",
 choices:[{text:"20", correct:true},{text:"60"},{text:"10"},{text:"3"}]},

{id:"l1d-eq-02", act:1, level:"L1", topic:"Equity", reading:"6.02 Security Market Indexes", difficulty:"easy", type:"exam",
 title:"How Indexes Weight",
 situation:"The S&P 500 is an example of which weighting method?",
 solution:"The S&P 500 is market-capitalization weighted (float-adjusted): each constituent's weight reflects its market value.",
 choices:[{text:"Market-capitalization weighted", correct:true},{text:"Price weighted"},{text:"Equal weighted"},{text:"Fundamentally weighted by earnings"}]},

{id:"l1d-eq-03", act:1, level:"L1", topic:"Equity", reading:"6.08 Equity Valuation: Concepts and Basic Tools", difficulty:"easy", type:"exam",
 title:"The P/E Ratio",
 situation:"A stock trades at $40 with EPS of $2. Its price-to-earnings ratio is:",
 solution:"P/E = Price / EPS = 40 / 2 = 20×.",
 choices:[{text:"20×", correct:true},{text:"0.05×"},{text:"2×"},{text:"80×"}]},

{id:"l1d-eq-04", act:1, level:"L1", topic:"Equity", reading:"6.08 Equity Valuation: Concepts and Basic Tools", difficulty:"easy", type:"exam",
 title:"Dividend Yield",
 situation:"A stock pays a $2 annual dividend and trades at $50. Its dividend yield is:",
 solution:"Dividend yield = Dividend / Price = 2 / 50 = 4.0%.",
 choices:[{text:"4.0%", correct:true},{text:"2.0%"},{text:"25.0%"},{text:"40.0%"}]},

{id:"l1d-eq-05", act:1, level:"L1", topic:"Equity", reading:"6.08 Equity Valuation (Gordon Growth)", difficulty:"moderate", type:"exam",
 title:"Constant-Growth Value",
 situation:"Next year's dividend (D₁) is $3.00, the required return is 10%, and the constant growth rate is 5%. The value is:",
 exhibit:{title:"Inputs", rows:[["D₁","$3.00"],["Required return (r)","10%"],["Growth (g)","5%"]]},
 solution:"V₀ = D₁/(r − g) = 3.00/(0.10 − 0.05) = 3.00/0.05 = $60.00. (D₁ is already next year's dividend.)",
 choices:[{text:"$60.00", correct:true},{text:"$30.00"},{text:"$66.00"},{text:"$57.00"}]},

{id:"l1d-eq-06", act:1, level:"L1", topic:"Equity", reading:"6.08 Equity Valuation (Justified P/E)", difficulty:"moderate", type:"exam",
 title:"Justified Leading P/E",
 situation:"With a dividend payout of 40%, required return 10%, and growth 4%, the justified leading P/E is:",
 solution:"Justified leading P/E = payout / (r − g) = 0.40 / (0.10 − 0.04) = 0.40 / 0.06 = 6.67×.",
 choices:[{text:"6.67×", correct:true},{text:"4.00×"},{text:"10.00×"},{text:"0.067×"}]},

{id:"l1d-eq-07", act:1, level:"L1", topic:"Equity", reading:"6.08 Equity Valuation (Multiples)", difficulty:"easy", type:"exam",
 title:"The PEG Ratio",
 situation:"A stock has a P/E of 20 and an expected earnings growth rate of 10 (percent). Its PEG ratio is:",
 solution:"PEG = P/E ÷ growth rate = 20 / 10 = 2.0. Lower PEG is generally considered cheaper for the growth.",
 choices:[{text:"2.0", correct:true},{text:"0.5"},{text:"200"},{text:"10"}]},

{id:"l1d-eq-08", act:1, level:"L1", topic:"Equity", reading:"6.08 Equity Valuation (Enterprise Value)", difficulty:"moderate", type:"exam",
 title:"Enterprise Value",
 situation:"A firm has market capitalization $500, total debt $100, and cash $20. Enterprise value is:",
 solution:"EV = Market cap + Total debt − Cash = 500 + 100 − 20 = $580.",
 choices:[{text:"$580", correct:true},{text:"$600"},{text:"$620"},{text:"$480"}]},

{id:"l1d-eq-09", act:1, level:"L1", topic:"Equity", reading:"6.03 Market Efficiency", difficulty:"easy", type:"exam",
 title:"Weak-Form Efficiency",
 situation:"If a market is weak-form efficient, which technique cannot consistently earn abnormal returns?",
 solution:"Weak-form efficiency means past prices are already reflected in the price, so technical analysis of past prices cannot consistently generate abnormal returns.",
 choices:[{text:"Technical analysis of past prices", correct:true},{text:"Trading on unpublished insider information"},{text:"Fundamental analysis of new filings"},{text:"Analyst site visits"}]},

{id:"l1d-eq-10", act:1, level:"L1", topic:"Equity", reading:"6.04 Overview of Equity Securities", difficulty:"easy", type:"exam",
 title:"Valuing a Preferred Share",
 situation:"A preferred share pays a fixed $5 annual dividend and investors require 8%. Its value is:",
 solution:"A fixed-dividend perpetual preferred is valued as a perpetuity: V = D / r = 5 / 0.08 = $62.50.",
 choices:[{text:"$62.50", correct:true},{text:"$40.00"},{text:"$5.00"},{text:"$8.00"}]},

/* ---------------- FIXED INCOME (11) ---------------- */
{id:"l1d-fi-01", act:1, level:"L1", topic:"Fixed Income", reading:"7.06 Fixed-Income Bond Valuation", difficulty:"easy", type:"exam",
 title:"Price and Yield",
 situation:"For an option-free fixed-rate bond, when market yields rise, the bond's price will:",
 solution:"Bond prices and yields move inversely: a rise in required yield lowers the present value of the bond's fixed cash flows.",
 choices:[{text:"Fall", correct:true},{text:"Rise"},{text:"Stay unchanged"},{text:"Rise then fall"}]},

{id:"l1d-fi-02", act:1, level:"L1", topic:"Fixed Income", reading:"7.07 Yield and Yield Spread Measures", difficulty:"easy", type:"exam",
 title:"Current Yield",
 situation:"A bond pays $60 in annual coupons and trades at $960. Its current yield is:",
 solution:"Current yield = Annual coupon / Price = 60 / 960 = 6.25%.",
 choices:[{text:"6.25%", correct:true},{text:"6.00%"},{text:"5.77%"},{text:"6.50%"}]},

{id:"l1d-fi-03", act:1, level:"L1", topic:"Fixed Income", reading:"7.06 Fixed-Income Bond Valuation", difficulty:"easy", type:"exam",
 title:"Discount Bond",
 situation:"A bond trades at a discount to par. Its coupon rate is:",
 solution:"A bond trades at a discount when its coupon rate is below its YTM; at a premium when coupon > YTM; at par when coupon = YTM.",
 choices:[{text:"Below its yield to maturity", correct:true},{text:"Above its yield to maturity"},{text:"Equal to its yield to maturity"},{text:"Equal to zero"}]},

{id:"l1d-fi-04", act:1, level:"L1", topic:"Fixed Income", reading:"7.06 Fixed-Income Bond Valuation", difficulty:"moderate", type:"exam",
 title:"Zero-Coupon Price",
 situation:"A zero-coupon bond with $1,000 face value matures in 3 years and yields 5% (annual). Its price is:",
 solution:"Price = FV / (1 + y)ⁿ = 1,000 / (1.05)³ = 1,000 / 1.157625 = $863.84.",
 choices:[{text:"$863.84", correct:true},{text:"$857.34"},{text:"$950.00"},{text:"$1,000.00"}]},

{id:"l1d-fi-05", act:1, level:"L1", topic:"Fixed Income", reading:"7.11 Yield-Based Bond Duration Measures", difficulty:"moderate", type:"exam",
 title:"Macaulay to Modified",
 situation:"A bond has a Macaulay duration of 5.0 and an annual yield of 5%. Its modified duration is:",
 solution:"Modified duration = Macaulay duration / (1 + y/k) = 5.0 / 1.05 = 4.76.",
 choices:[{text:"4.76", correct:true},{text:"5.00"},{text:"5.25"},{text:"4.50"}]},

{id:"l1d-fi-06", act:1, level:"L1", topic:"Fixed Income", reading:"7.11 Yield-Based Bond Duration Measures", difficulty:"easy", type:"exam",
 title:"Duration Price Impact",
 situation:"A bond has modified duration 6.0. If yields rise 25 bps, the approximate price change is:",
 solution:"%ΔPrice ≈ −ModDur × Δy = −6.0 × 0.0025 = −0.015 = −1.5%.",
 choices:[{text:"−1.5%", correct:true},{text:"+1.5%"},{text:"−6.0%"},{text:"−0.15%"}]},

{id:"l1d-fi-07", act:1, level:"L1", topic:"Fixed Income", reading:"7.12 Yield-Based Bond Convexity", difficulty:"moderate", type:"exam",
 title:"Positive Convexity",
 situation:"For an option-free bond with positive convexity, the actual price change versus the duration-only estimate is:",
 solution:"Positive convexity means the price rises more than duration predicts when yields fall, and falls less than predicted when yields rise — a benefit to the holder.",
 choices:[{text:"More favorable than duration alone predicts", correct:true},{text:"Always exactly equal to duration"},{text:"Less favorable than duration predicts"},{text:"Unrelated to yield changes"}]},

{id:"l1d-fi-08", act:1, level:"L1", topic:"Fixed Income", reading:"7.14 Credit Risk", difficulty:"easy", type:"exam",
 title:"The Credit Spread",
 situation:"A corporate bond yields 7.0%; the comparable Treasury yields 4.5%. The credit spread is:",
 solution:"Credit spread = corporate yield − risk-free yield = 7.0% − 4.5% = 2.5% = 250 bps.",
 choices:[{text:"250 bps", correct:true},{text:"25 bps"},{text:"115 bps"},{text:"300 bps"}]},

{id:"l1d-fi-09", act:1, level:"L1", topic:"Fixed Income", reading:"7.05 Fixed-Income Markets for Government Issuers", difficulty:"easy", type:"exam",
 title:"Nominal Spread",
 situation:"The nominal (benchmark) spread on a corporate bond is measured relative to:",
 solution:"The nominal spread is the difference between the bond's YTM and the YTM of a government (Treasury) bond of comparable maturity.",
 choices:[{text:"A government bond of comparable maturity", correct:true},{text:"The bond's own coupon rate"},{text:"The inflation rate"},{text:"The equity risk premium"}]},

{id:"l1d-fi-10", act:1, level:"L1", topic:"Fixed Income", reading:"7.07 Yield and Yield Spread Measures", difficulty:"hard", type:"exam",
 title:"T-Bill Bond-Equivalent Yield",
 situation:"A 90-day T-bill with $1,000 face value is priced at $990. Its bond-equivalent (365-day) yield is approximately:",
 exhibit:{title:"Inputs", rows:[["Face value","$1,000"],["Price","$990"],["Days to maturity","90"]]},
 solution:"Holding-period yield = (1,000 − 990)/990 = 1.0101%. Annualized: 1.0101% × 365/90 ≈ 4.10%.",
 choices:[{text:"4.10%", correct:true},{text:"1.01%"},{text:"4.04%"},{text:"10.00%"}]},

{id:"l1d-fi-11", act:1, level:"L1", topic:"Fixed Income", reading:"7.17 Fixed-Income Securitization", difficulty:"moderate", type:"exam",
 title:"Why Securitize",
 situation:"A key benefit of securitizing assets through a special purpose entity (SPE) is that the assets become:",
 solution:"A properly structured SPE is bankruptcy-remote: the securitized assets are isolated from the originator's credit, typically lowering funding costs.",
 choices:[{text:"Bankruptcy-remote from the originator", correct:true},{text:"Guaranteed by the government"},{text:"Free of all credit risk"},{text:"Exempt from interest rate risk"}]},

/* ---------------- DERIVATIVES (10) ---------------- */
{id:"l1d-dv-01", act:1, level:"L1", topic:"Derivatives", reading:"7.11 Arbitrage, Replication, Cost of Carry", difficulty:"easy", type:"exam",
 title:"No-Arbitrage Forward",
 situation:"A non-dividend stock trades at $50; the annual risk-free rate is 6%. The no-arbitrage 1-year forward price is:",
 solution:"F₀ = S₀(1 + r) = 50 × 1.06 = $53.00.",
 choices:[{text:"$53.00", correct:true},{text:"$50.00"},{text:"$47.00"},{text:"$56.00"}]},

{id:"l1d-dv-02", act:1, level:"L1", topic:"Derivatives", reading:"7.09 Contingent Claims (Options)", difficulty:"easy", type:"exam",
 title:"Long Call Profit",
 situation:"You buy a call with a $50 strike for a $3 premium. At expiry the stock is $60. Your profit is:",
 solution:"Call profit = max(0, S − X) − premium = (60 − 50) − 3 = $7 per share.",
 choices:[{text:"$7", correct:true},{text:"$10"},{text:"−$3"},{text:"$17"}]},

{id:"l1d-dv-03", act:1, level:"L1", topic:"Derivatives", reading:"7.09 Contingent Claims (Options)", difficulty:"easy", type:"exam",
 title:"Long Put Profit",
 situation:"You buy a put with a $50 strike for a $2 premium. At expiry the stock is $40. Your profit is:",
 solution:"Put profit = max(0, X − S) − premium = (50 − 40) − 2 = $8 per share.",
 choices:[{text:"$8", correct:true},{text:"$10"},{text:"−$2"},{text:"−$8"}]},

{id:"l1d-dv-04", act:1, level:"L1", topic:"Derivatives", reading:"7.16 Option Replication Using Put–Call Parity", difficulty:"moderate", type:"exam",
 title:"Put–Call Parity",
 situation:"A call is worth $5, the stock is $50, and the present value of the strike is $48. By put–call parity, the put is worth:",
 solution:"Put–call parity: C + PV(X) = P + S → P = C + PV(X) − S = 5 + 48 − 50 = $3.",
 choices:[{text:"$3", correct:true},{text:"$7"},{text:"$5"},{text:"$2"}]},

{id:"l1d-dv-05", act:1, level:"L1", topic:"Derivatives", reading:"7.08 Derivative Instrument Features (Futures)", difficulty:"easy", type:"exam",
 title:"Futures vs Forwards",
 situation:"Compared with a forward contract, an exchange-traded futures contract is:",
 solution:"Futures are standardized, exchange-traded, and marked to market daily through a clearinghouse, which reduces counterparty risk versus a customized OTC forward.",
 choices:[{text:"Standardized and marked to market daily", correct:true},{text:"Fully customized and settled only at expiry"},{text:"Free of margin requirements"},{text:"Always more expensive"}]},

{id:"l1d-dv-06", act:1, level:"L1", topic:"Derivatives", reading:"7.09 Forward Commitments (Swaps)", difficulty:"easy", type:"exam",
 title:"The Plain-Vanilla Swap",
 situation:"In a plain-vanilla interest rate swap, the two parties exchange:",
 solution:"A plain-vanilla interest rate swap exchanges a stream of fixed-rate payments for a stream of floating-rate payments on a notional principal.",
 choices:[{text:"Fixed-rate payments for floating-rate payments", correct:true},{text:"Two different currencies' principals only"},{text:"Equity returns for commodity returns"},{text:"Stock for bonds"}]},

{id:"l1d-dv-07", act:1, level:"L1", topic:"Derivatives", reading:"7.09 Contingent Claims (Options)", difficulty:"easy", type:"exam",
 title:"In the Money",
 situation:"A call option is in the money when:",
 solution:"A call is in the money when the underlying price exceeds the strike (S > X); its intrinsic value is max(0, S − X).",
 choices:[{text:"The stock price exceeds the strike price", correct:true},{text:"The stock price is below the strike price"},{text:"The stock price equals the strike price"},{text:"The premium exceeds the strike"}]},

{id:"l1d-dv-08", act:1, level:"L1", topic:"Derivatives", reading:"7.11 Cost of Carry", difficulty:"hard", type:"exam",
 title:"Forward With a Dividend",
 situation:"A stock is $100, the risk-free rate is 5%, and the present value of dividends over the year is $2. The no-arbitrage 1-year forward price is:",
 exhibit:{title:"Inputs", rows:[["Spot","$100"],["Risk-free rate","5%"],["PV of dividends","$2"]]},
 solution:"F₀ = (S₀ − PV of income)(1 + r) = (100 − 2) × 1.05 = 98 × 1.05 = $102.90. Income reduces the carry cost.",
 choices:[{text:"$102.90", correct:true},{text:"$105.00"},{text:"$100.90"},{text:"$103.00"}]},

{id:"l1d-dv-09", act:1, level:"L1", topic:"Derivatives", reading:"7.09 Contingent Claims (Options)", difficulty:"easy", type:"exam",
 title:"Intrinsic Value",
 situation:"A call with a $50 strike is written on a stock trading at $45. The call's intrinsic value is:",
 solution:"Call intrinsic value = max(0, S − X) = max(0, 45 − 50) = $0 (it is out of the money).",
 choices:[{text:"$0", correct:true},{text:"−$5"},{text:"$5"},{text:"$45"}]},

{id:"l1d-dv-10", act:1, level:"L1", topic:"Derivatives", reading:"7.10 Derivative Benefits, Risks, and Uses", difficulty:"easy", type:"exam",
 title:"Why Use Derivatives",
 situation:"Which is a commonly cited benefit of derivatives markets?",
 solution:"Derivatives allow low-cost risk transfer (hedging), aid price discovery, and offer operational efficiency and leverage relative to trading the underlying.",
 choices:[{text:"Efficient risk transfer and price discovery", correct:true},{text:"Elimination of all market risk"},{text:"Guaranteed profits"},{text:"Removal of counterparty exposure entirely"}]},

/* ---------------- ALTERNATIVES (9) ---------------- */
{id:"l1d-ai-01", act:1, level:"L1", topic:"Alternatives", reading:"9.06 Hedge Funds", difficulty:"moderate", type:"exam",
 title:"Two and Twenty",
 situation:"A hedge fund charges 2% management (on assets) plus 20% incentive on gains. On $100M that returns 20%, total fees are:",
 exhibit:{title:"Inputs", rows:[["Assets","$100M"],["Return","20%"],["Management fee","2% of assets"],["Incentive fee","20% of gains"]]},
 solution:"Management fee = 2% × 100M = $2M. Incentive = 20% × (20% × 100M) = 20% × 20M = $4M. Total = $6M.",
 choices:[{text:"$6M", correct:true},{text:"$4M"},{text:"$2M"},{text:"$4.4M"}]},

{id:"l1d-ai-02", act:1, level:"L1", topic:"Alternatives", reading:"9.03 Investments in Private Capital", difficulty:"easy", type:"exam",
 title:"The J-Curve",
 situation:"The 'J-curve' commonly seen in private equity funds refers to:",
 solution:"The J-curve: early returns are negative (fees and initial write-downs) before value creation and exits produce positive returns later in the fund's life.",
 choices:[{text:"Negative early returns turning positive later", correct:true},{text:"Steadily rising returns from year one"},{text:"A permanent loss of capital"},{text:"Returns that mirror public equities exactly"}]},

{id:"l1d-ai-03", act:1, level:"L1", topic:"Alternatives", reading:"9.04 Real Estate and Infrastructure", difficulty:"easy", type:"exam",
 title:"The Cap Rate",
 situation:"A property generates $100,000 net operating income and is valued at $1,250,000. Its capitalization rate is:",
 solution:"Cap rate = NOI / Property value = 100,000 / 1,250,000 = 8.0%.",
 choices:[{text:"8.0%", correct:true},{text:"12.5%"},{text:"10.0%"},{text:"0.8%"}]},

{id:"l1d-ai-04", act:1, level:"L1", topic:"Alternatives", reading:"9.04 Real Estate and Infrastructure", difficulty:"moderate", type:"exam",
 title:"Value From the Cap Rate",
 situation:"A property's net operating income is $120,000 and the market cap rate is 6%. Using direct capitalization, its value is:",
 solution:"Value = NOI / cap rate = 120,000 / 0.06 = $2,000,000.",
 choices:[{text:"$2,000,000", correct:true},{text:"$720,000"},{text:"$1,200,000"},{text:"$2,500,000"}]},

{id:"l1d-ai-05", act:1, level:"L1", topic:"Alternatives", reading:"9.05 Natural Resources (Commodities)", difficulty:"moderate", type:"exam",
 title:"Contango and Roll Yield",
 situation:"When a commodity futures curve is in contango, the roll return to a long futures investor is generally:",
 solution:"In contango, longer-dated futures cost more than near-dated; rolling expiring contracts forward locks in a loss, producing a negative roll return.",
 choices:[{text:"Negative", correct:true},{text:"Positive"},{text:"Zero"},{text:"Equal to the risk-free rate"}]},

{id:"l1d-ai-06", act:1, level:"L1", topic:"Alternatives", reading:"9.06 Hedge Funds", difficulty:"easy", type:"exam",
 title:"High-Water Mark",
 situation:"A hedge fund's high-water mark means the incentive fee is charged only when:",
 solution:"A high-water mark ensures incentive fees apply only on gains above the fund's previous peak value, so investors are not charged twice for recovering prior losses.",
 choices:[{text:"The fund's value exceeds its previous peak", correct:true},{text:"The fund posts any positive month"},{text:"The manager decides to charge it"},{text:"Assets under management grow"}]},

{id:"l1d-ai-07", act:1, level:"L1", topic:"Alternatives", reading:"9.07 Introduction to Digital Assets", difficulty:"easy", type:"exam",
 title:"What a Blockchain Is",
 situation:"A blockchain is best described as:",
 solution:"A blockchain is a distributed, cryptographically secured ledger shared across a network, with no single central recordkeeper.",
 choices:[{text:"A distributed digital ledger", correct:true},{text:"A central bank database"},{text:"A type of equity security"},{text:"A government-issued currency"}]},

{id:"l1d-ai-08", act:1, level:"L1", topic:"Alternatives", reading:"9.01 Alternative Investment Features and Structures", difficulty:"easy", type:"exam",
 title:"Fund of Funds",
 situation:"A fund of hedge funds provides diversification but has the drawback of:",
 solution:"A fund of funds adds a second layer of fees (its own on top of the underlying funds'), which can materially reduce net returns.",
 choices:[{text:"An additional layer of fees", correct:true},{text:"No diversification benefit"},{text:"Guaranteed underperformance of the risk-free rate"},{text:"Daily liquidity always"}]},

{id:"l1d-ai-09", act:1, level:"L1", topic:"Alternatives", reading:"9.03 Investments in Private Capital — Debt", difficulty:"moderate", type:"exam",
 title:"Where Mezzanine Sits",
 situation:"Relative to senior secured debt, mezzanine (subordinated) debt generally has:",
 solution:"Mezzanine debt is subordinate in the capital structure, bearing more risk and therefore requiring a higher yield than senior secured debt.",
 choices:[{text:"Higher risk and a higher required yield", correct:true},{text:"Lower risk and a lower yield"},{text:"The same priority as senior debt"},{text:"No credit risk"}]},

/* ---------------- PORTFOLIO MANAGEMENT (9) ---------------- */
{id:"l1d-pm-01", act:1, level:"L1", topic:"Portfolio Management", reading:"3.01 Portfolio Risk and Return, Part I", difficulty:"easy", type:"exam",
 title:"Two-Asset Return",
 situation:"A portfolio is 60% in an asset returning 10% and 40% in one returning 5%. Its expected return is:",
 solution:"E[Rₚ] = Σ wᵢRᵢ = 0.60×10% + 0.40×5% = 6% + 2% = 8.0%.",
 choices:[{text:"8.0%", correct:true},{text:"7.5%"},{text:"15.0%"},{text:"6.0%"}]},

{id:"l1d-pm-02", act:1, level:"L1", topic:"Portfolio Management", reading:"3.01 Portfolio Risk and Return, Part I", difficulty:"easy", type:"exam",
 title:"When Diversification Wins",
 situation:"The risk-reduction benefit of combining two assets in a portfolio is greatest when their correlation is:",
 solution:"Diversification benefit is largest at correlation −1 (perfect negative), where offsetting moves can dramatically reduce portfolio variance.",
 choices:[{text:"−1.0", correct:true},{text:"+1.0"},{text:"0.0"},{text:"+0.5"}]},

{id:"l1d-pm-03", act:1, level:"L1", topic:"Portfolio Management", reading:"3.02 Portfolio Risk and Return, Part II", difficulty:"easy", type:"exam",
 title:"CAPM Required Return",
 situation:"With a risk-free rate of 4%, expected market return 9%, and beta 0.8, the CAPM required return is:",
 solution:"E[R] = R_f + β(E[Rₘ] − R_f) = 4% + 0.8×(9% − 4%) = 4% + 4% = 8.0%.",
 choices:[{text:"8.0%", correct:true},{text:"9.0%"},{text:"7.2%"},{text:"4.0%"}]},

{id:"l1d-pm-04", act:1, level:"L1", topic:"Portfolio Management", reading:"3.02 Portfolio Risk and Return, Part II", difficulty:"easy", type:"exam",
 title:"Beta Benchmarks",
 situation:"The beta of the overall market portfolio is:",
 solution:"By definition the market portfolio has a beta of 1.0; the risk-free asset has a beta of 0.",
 choices:[{text:"1.0", correct:true},{text:"0.0"},{text:"Greater than 1.0 always"},{text:"Undefined"}]},

{id:"l1d-pm-05", act:1, level:"L1", topic:"Portfolio Management", reading:"3.01 Portfolio Risk and Return, Part I", difficulty:"easy", type:"exam",
 title:"What Diversification Removes",
 situation:"Adding many imperfectly correlated securities to a portfolio primarily reduces:",
 solution:"Diversification eliminates unsystematic (firm-specific) risk; systematic (market) risk remains and is what CAPM prices.",
 choices:[{text:"Unsystematic (firm-specific) risk", correct:true},{text:"Systematic (market) risk"},{text:"The risk-free rate"},{text:"Inflation risk only"}]},

{id:"l1d-pm-06", act:1, level:"L1", topic:"Portfolio Management", reading:"3.01 Portfolio Risk and Return, Part I", difficulty:"easy", type:"exam",
 title:"Sharpe Ratio",
 situation:"A portfolio returns 11% with an 16% standard deviation; the risk-free rate is 3%. Its Sharpe ratio is:",
 solution:"Sharpe = (Rₚ − R_f)/σ = (11% − 3%)/16% = 8/16 = 0.50.",
 choices:[{text:"0.50", correct:true},{text:"0.69"},{text:"0.19"},{text:"0.60"}]},

{id:"l1d-pm-07", act:1, level:"L1", topic:"Portfolio Management", reading:"Basics of Portfolio Planning and Construction", difficulty:"moderate", type:"exam",
 title:"Ability vs Willingness",
 situation:"An investor's risk tolerance in the IPS is best assessed by combining:",
 solution:"Risk tolerance reflects both the ability to take risk (wealth, horizon, liquidity needs) and the willingness to take risk (attitudes). When they conflict, the lower usually governs.",
 choices:[{text:"Ability and willingness to take risk", correct:true},{text:"Past returns only"},{text:"The benchmark's volatility"},{text:"The manager's fee schedule"}]},

{id:"l1d-pm-08", act:1, level:"L1", topic:"Portfolio Management", reading:"The Behavioral Biases of Individuals", difficulty:"easy", type:"exam",
 title:"Loss Aversion",
 situation:"Loss aversion describes an investor who:",
 solution:"Loss aversion: the pain of a loss is felt more intensely than the pleasure of an equal-sized gain, which can distort risk-taking and selling decisions.",
 choices:[{text:"Feels losses more strongly than equivalent gains", correct:true},{text:"Ignores losses entirely"},{text:"Prefers guaranteed losses"},{text:"Is indifferent between gains and losses"}]},

{id:"l1d-pm-09", act:1, level:"L1", topic:"Portfolio Management", reading:"3.01 Portfolio Risk and Return, Part I", difficulty:"moderate", type:"exam",
 title:"No Diversification",
 situation:"If two assets are perfectly positively correlated (ρ = +1), the portfolio standard deviation equals:",
 solution:"At ρ = +1 there is no diversification benefit: portfolio standard deviation is just the weighted average of the two assets' standard deviations.",
 choices:[{text:"The weighted average of the individual standard deviations", correct:true},{text:"Zero"},{text:"Always less than either asset's"},{text:"The sum of the two variances"}]}

);
